"""SlackClient — low-level Slack Web API access for integrations and skills."""

import base64
import html
import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

_SLACK_LINK_RE = re.compile(r"<(https?://[^>|]+)(?:\|[^>]*)?>")
_BARE_URL_RE = re.compile(r"https?://[^\s<>]+")


def _clean_bare_url(url: str) -> str:
    """Strip punctuation/mrkdwn that belongs to surrounding prose, not the URL."""
    trailing = ".,;:!?'\"*_]"
    url = url.rstrip(trailing)
    while url.endswith(")") and url.count(")") > url.count("("):
        url = url[:-1].rstrip(trailing)
    return url


def _extract_message_text(msg: dict) -> str:
    """Extract the best available text from a Slack message.

    Bot messages using Block Kit carry full content in msg['blocks'] while
    msg['text'] is a truncated notification fallback generated by Slack.
    For human messages (no blocks) msg['text'] is authoritative.
    """
    blocks = msg.get("blocks")
    if blocks:
        # rich_text blocks signal a human-typed message or a workflow message whose full
        # content lives in msg["text"] (or nested elements we don't walk). Bail out early
        # so we don't return a partial header and silently drop the body.
        if any(block.get("type") == "rich_text" for block in blocks):
            return msg.get("text", "").strip()

        parts = []
        for block in blocks:
            # section.text — single text object
            block_text = block.get("text")
            if isinstance(block_text, dict):
                parts.append(block_text.get("text", ""))
            # section.fields — list of text objects (used in status/approval cards)
            fields = block.get("fields")
            if isinstance(fields, list):
                for field in fields:
                    if isinstance(field, dict):
                        parts.append(field.get("text", ""))
        text = "\n".join(p for p in parts if p).strip()
        if text:
            return text
    return msg.get("text", "").strip()


def _extract_links(msg: dict) -> list[str]:
    """Collect external links from attachments, blocks, and message text."""
    links: list[str] = []
    for att in msg.get("attachments") or []:
        if not isinstance(att, dict):
            continue
        for key in ("title_link", "from_url", "original_url"):
            url = att.get(key)
            if isinstance(url, str) and url.startswith("http"):
                links.append(url)

    text = _extract_message_text(msg)
    links.extend(m.group(1) for m in _SLACK_LINK_RE.finditer(text))
    # Bare URLs (Slack leaves bot/attachment text unwrapped): scan the text with
    # Slack-formatted links blanked out so they aren't double-counted or mangled.
    bare_text = _SLACK_LINK_RE.sub(" ", text)
    links.extend(_clean_bare_url(url) for url in _BARE_URL_RE.findall(bare_text))

    seen: set[str] = set()
    deduped: list[str] = []
    for link in links:
        # Slack escapes &, <, > as HTML entities in message text; unescape so
        # extracted URLs (e.g. query params with &amp;) are usable as-is.
        link = html.unescape(link)
        if link not in seen:
            seen.add(link)
            deduped.append(link)
    return deduped


def _message_sender_name(msg: dict, user_map: dict[str, str]) -> str:
    """Resolve a display name for human and bot/integration messages."""
    if uid := msg.get("user"):
        return user_map.get(uid, uid)
    if username := msg.get("username"):
        return username
    bot_profile = msg.get("bot_profile") or {}
    if isinstance(bot_profile, dict):
        if name := bot_profile.get("name"):
            return name
    if bot_id := msg.get("bot_id"):
        return f"bot:{bot_id}"
    return "unknown"


class SlackClient:
    """Thin wrapper around slack_sdk.WebClient for Slack API calls.

    Used by both SlackAdapterBase (internally) and skills (via adapter.slack_client).
    """

    # Per-request HTTP timeout (seconds). slack_sdk defaults to 30s, which lets a
    # paginated get_history_window (up to max_pages requests) hang for minutes;
    # 10s bounds each call and a mid-scan timeout surfaces as truncated_reason.
    _REQUEST_TIMEOUT = 10

    def __init__(self, bot_token: str):
        from slack_sdk import WebClient
        self._token = bot_token
        self._client = WebClient(token=bot_token, timeout=self._REQUEST_TIMEOUT)

    def get_history_window(
        self,
        channel_id: str,
        *,
        limit: int = 200,
        oldest: str | None = None,
        latest: str | None = None,
        max_pages: int = 10,
    ) -> dict[str, Any]:
        """Fetch channel history with pagination, time bounds, and structured output.

        Returns messages oldest-first with per-message links and coverage metadata.

        Truncation semantics: when `oldest` is set, Slack paginates forward from
        the oldest end of the window, so hitting `limit` or `max_pages` drops the
        NEWEST messages in the window (coverage.newest_ts will lag the window end).
        Without `oldest`, pagination walks backward from now and truncation drops
        the oldest messages instead. Check coverage.has_more / truncated_reason.
        """
        total_limit = max(1, min(int(limit), 1000))
        raw_messages: list[dict] = []
        cursor: str | None = None
        pages_fetched = 0
        truncated_reason: str | None = None
        has_more = False

        try:
            while pages_fetched < max(1, int(max_pages)):
                if len(raw_messages) >= total_limit:
                    has_more = True
                    truncated_reason = truncated_reason or "limit"
                    break

                remaining = total_limit - len(raw_messages)
                page_limit = max(1, min(remaining, 1000))
                kwargs: dict[str, Any] = {"channel": channel_id, "limit": page_limit}
                if oldest:
                    kwargs["oldest"] = oldest
                if latest:
                    kwargs["latest"] = latest
                if cursor:
                    kwargs["cursor"] = cursor

                resp = self._client.conversations_history(**kwargs)
                if not resp.get("ok"):
                    logger.warning(
                        "conversations_history error for %s: %s",
                        channel_id,
                        resp.get("error"),
                    )
                    if not raw_messages:
                        return {
                            "messages": [],
                            "coverage": {
                                "count": 0,
                                "oldest_ts": None,
                                "newest_ts": None,
                                "has_more": False,
                                "pages_fetched": pages_fetched,
                                "truncated_reason": resp.get("error"),
                            },
                            "user_map": {},
                        }
                    truncated_reason = resp.get("error")
                    break

                raw_messages.extend(resp.get("messages", []))
                pages_fetched += 1
                cursor = resp.get("response_metadata", {}).get("next_cursor") or None

                if len(raw_messages) >= total_limit:
                    raw_messages = raw_messages[:total_limit]
                    if cursor:
                        has_more = True
                        truncated_reason = truncated_reason or "limit"
                    break
                if not cursor:
                    break
            else:
                if cursor:
                    has_more = True
                    truncated_reason = truncated_reason or "max_pages"
        except Exception as exc:
            logger.warning("Failed to fetch history for channel %s: %s", channel_id, exc)
            if not raw_messages:
                return {
                    "messages": [],
                    "coverage": {
                        "count": 0,
                        "oldest_ts": None,
                        "newest_ts": None,
                        "has_more": False,
                        "pages_fetched": pages_fetched,
                        "truncated_reason": str(exc),
                    },
                    "user_map": {},
                }
            truncated_reason = truncated_reason or str(exc)

        all_user_ids: set[str] = set()
        for msg in raw_messages:
            if uid := msg.get("user"):
                all_user_ids.add(uid)
            for mentioned in re.findall(r"<@([A-Z0-9]+)>", _extract_message_text(msg)):
                all_user_ids.add(mentioned)

        user_map = self.resolve_user_ids(all_user_ids)

        def _replace_mentions(text: str) -> str:
            return re.sub(
                r"<@([A-Z0-9]+)>",
                lambda m: f"@{user_map.get(m.group(1), m.group(1))}",
                text,
            )

        def _ts_key(msg: dict) -> float:
            try:
                return float(msg.get("ts") or 0)
            except (TypeError, ValueError):
                return 0.0

        structured: list[dict[str, Any]] = []
        timestamps: list[str] = []
        # Sort by ts rather than reversing page order: with `oldest` set, Slack
        # paginates forward (later pages are newer) while each page is internally
        # newest-first, so concatenated page order is not chronological. Sorting
        # over the reversed list keeps ts-less messages ordered among themselves
        # as before (stable sort); real Slack messages always carry ts.
        for msg in sorted(reversed(raw_messages), key=_ts_key):
            text = _replace_mentions(_extract_message_text(msg)).strip()
            if not text:
                continue
            ts = msg.get("ts", "")
            if ts:
                timestamps.append(ts)
            structured.append({
                "user": _message_sender_name(msg, user_map),
                "text": text,
                "ts": ts,
                "links": _extract_links(msg),
            })

        return {
            "messages": structured,
            "coverage": {
                "count": len(structured),
                "oldest_ts": timestamps[0] if timestamps else None,
                "newest_ts": timestamps[-1] if timestamps else None,
                "has_more": has_more,
                "pages_fetched": pages_fetched,
                "truncated_reason": truncated_reason,
            },
            "user_map": user_map,
        }

    def get_history(self, channel_id: str, limit: int) -> tuple[list[str], dict[str, str]]:
        """
        Fetch recent messages from a channel.

        Returns (formatted_messages, user_id_to_name_map).
        User IDs in messages are replaced with real display names.
        """
        window = self.get_history_window(channel_id, limit=limit, max_pages=1)
        formatted = [
            f"{msg['user']}: {msg['text']}"
            for msg in window.get("messages", [])
        ]
        return formatted, window.get("user_map", {})

    @staticmethod
    def _is_valid_slack_ts(ts: str) -> bool:
        """Slack timestamps are Unix epoch floats like '1234567890.123456'."""
        try:
            float(ts)
            return "." in ts
        except (ValueError, TypeError):
            return False

    def post_message(self, channel_id: str, text: str, thread_ts: str | None = None) -> dict:
        """Post a message to a Slack channel or thread."""
        kwargs: dict = {"channel": channel_id, "text": text}
        if thread_ts:
            if self._is_valid_slack_ts(thread_ts):
                kwargs["thread_ts"] = thread_ts
            else:
                logger.warning("Ignoring invalid thread_ts %r — must be a Slack timestamp float", thread_ts)
        try:
            resp = self._client.chat_postMessage(**kwargs)
            return {"ok": resp.get("ok", False), "ts": resp.get("ts", ""), "channel": channel_id}
        except Exception:
            logger.warning("Failed to post message to %s", channel_id, exc_info=True)
            return {"ok": False, "error": "post_message failed", "channel": channel_id}

    def get_thread_replies(self, channel_id: str, thread_ts: str, limit: int = 100) -> list[str]:
        """Fetch messages in a thread, oldest-first, formatted as 'name: text'.

        Returns [] on error or when the API returns not-ok.
        """
        if not self._is_valid_slack_ts(thread_ts):
            logger.warning("Ignoring invalid thread_ts %r for get_thread_replies", thread_ts)
            return []
        try:
            resp = self._client.conversations_replies(channel=channel_id, ts=thread_ts, limit=limit)
        except Exception:
            logger.warning("Failed to fetch thread replies for %s/%s", channel_id, thread_ts, exc_info=True)
            return []

        if not resp.get("ok"):
            logger.warning("conversations_replies error: %s", resp.get("error"))
            return []

        messages = resp.get("messages", [])
        all_user_ids: set[str] = {msg["user"] for msg in messages if msg.get("user")}
        user_map = self.resolve_user_ids(all_user_ids)

        lines = []
        for msg in messages:  # already oldest-first from Slack
            uid = msg.get("user", "unknown")
            name = user_map.get(uid, uid).lower()
            text = _extract_message_text(msg)
            if text:
                lines.append(f"{name}: {text}")
        return lines

    def get_members(self, channel_id: str) -> list[dict]:
        """Fetch all members of a channel with their display names.

        Returns a list of {id, name} dicts, sorted by name.
        Handles pagination automatically.
        """
        user_ids: set[str] = set()
        cursor = None
        try:
            while True:
                kwargs: dict = {"channel": channel_id, "limit": 200}
                if cursor:
                    kwargs["cursor"] = cursor
                resp = self._client.conversations_members(**kwargs)
                if not resp.get("ok"):
                    logger.warning("conversations_members error for %s: %s", channel_id, resp.get("error"))
                    break
                user_ids.update(resp.get("members", []))
                cursor = resp.get("response_metadata", {}).get("next_cursor")
                if not cursor:
                    break
        except Exception as exc:
            logger.warning("Failed to fetch members for channel %s: %s", channel_id, exc)

        user_map = self.resolve_user_ids(user_ids)
        return sorted(
            [{"id": uid, "name": name} for uid, name in user_map.items()],
            key=lambda m: m["name"].lower(),
        )

    # Slack image MIME types accepted by Claude's vision API
    _SUPPORTED_IMAGE_TYPES = {"image/png", "image/jpeg", "image/gif", "image/webp"}

    def download_images(self, files: list[dict]) -> list[dict]:
        """Download image files from a Slack message and return base64-encoded dicts.

        Each returned dict has keys: data (base64 str), media_type (str).
        Non-image files and unsupported types are silently skipped.
        """
        import urllib.request

        results = []
        for f in files:
            mimetype = f.get("mimetype", "")
            if mimetype not in self._SUPPORTED_IMAGE_TYPES:
                continue
            url = f.get("url_private")
            if not url:
                continue
            try:
                req = urllib.request.Request(
                    url,
                    headers={"Authorization": f"Bearer {self._token}"},
                )
                with urllib.request.urlopen(req, timeout=10) as resp:
                    raw = resp.read()
                encoded = base64.b64encode(raw).decode("ascii")
                logger.info("Downloaded image %s (%s, %d bytes)", mimetype, url[:80], len(raw))
                results.append({
                    "data": encoded,
                    "media_type": mimetype,
                })
            except Exception as exc:
                logger.warning("Failed to download Slack image %s: %s", url, exc)
        return results

    def resolve_user_ids(self, user_ids: set[str]) -> dict[str, str]:
        """Return a map of user_id -> display_name for the given set of IDs."""
        result = {}
        for uid in user_ids:
            try:
                resp = self._client.users_info(user=uid)
                profile = resp["user"].get("profile", {})
                name = (
                    profile.get("display_name")
                    or profile.get("real_name")
                    or resp["user"].get("name")
                    or uid
                )
                result[uid] = name
            except Exception:
                result[uid] = uid
        return result
